// <auto-generated />
using System;
using EstoqueApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EstoqueApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250405183504_CreateDataBase")]
    partial class CreateDataBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EstoqueApi.Models.Custumer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Email");

                    b.Property<DateTime>("Lastpurchase")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Name");

                    b.Property<int?>("TennisId")
                        .HasColumnType("int");

                    b.Property<int>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("Int")
                        .HasColumnName("ZipCode");

                    b.HasKey("Id");

                    b.HasIndex("TennisId");

                    b.HasIndex(new[] { "Email" }, "IX_Custumer_Email")
                        .IsUnique();

                    b.ToTable("Custumer", (string)null);
                });

            modelBuilder.Entity("EstoqueApi.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustumerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateSale")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(60)
                        .HasColumnType("SMALLDATETIME")
                        .HasColumnName("DateSale")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Description");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<int>("TennisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustumerId");

                    b.HasIndex("SellerId");

                    b.HasIndex("TennisId");

                    b.HasIndex(new[] { "Id" }, "IX_Sale_Id")
                        .IsUnique();

                    b.ToTable("Sale", (string)null);
                });

            modelBuilder.Entity("EstoqueApi.Models.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSale")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TennisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TennisId");

                    b.ToTable("Seller");
                });

            modelBuilder.Entity("EstoqueApi.Models.Tennis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Name");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("Price");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "IX_Tennis_Id")
                        .IsUnique();

                    b.ToTable("Tennis", (string)null);
                });

            modelBuilder.Entity("EstoqueApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Password");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "IX_User_Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("UserSeller", b =>
                {
                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SellerId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSeller");
                });

            modelBuilder.Entity("EstoqueApi.Models.Custumer", b =>
                {
                    b.HasOne("EstoqueApi.Models.Tennis", null)
                        .WithMany("Custumers")
                        .HasForeignKey("TennisId");
                });

            modelBuilder.Entity("EstoqueApi.Models.Sale", b =>
                {
                    b.HasOne("EstoqueApi.Models.Custumer", null)
                        .WithMany("sales")
                        .HasForeignKey("CustumerId");

                    b.HasOne("EstoqueApi.Models.Seller", "sellers")
                        .WithMany("sales")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Sale_Seller");

                    b.HasOne("EstoqueApi.Models.Tennis", "Tennis")
                        .WithMany("sales")
                        .HasForeignKey("TennisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Sale_Tennis");

                    b.Navigation("Tennis");

                    b.Navigation("sellers");
                });

            modelBuilder.Entity("EstoqueApi.Models.Seller", b =>
                {
                    b.HasOne("EstoqueApi.Models.Tennis", null)
                        .WithMany("sellers")
                        .HasForeignKey("TennisId");
                });

            modelBuilder.Entity("UserSeller", b =>
                {
                    b.HasOne("EstoqueApi.Models.Seller", null)
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Fk_UserSller_SellerId");

                    b.HasOne("EstoqueApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Fk_UserSller_UserId");
                });

            modelBuilder.Entity("EstoqueApi.Models.Custumer", b =>
                {
                    b.Navigation("sales");
                });

            modelBuilder.Entity("EstoqueApi.Models.Seller", b =>
                {
                    b.Navigation("sales");
                });

            modelBuilder.Entity("EstoqueApi.Models.Tennis", b =>
                {
                    b.Navigation("Custumers");

                    b.Navigation("sales");

                    b.Navigation("sellers");
                });
#pragma warning restore 612, 618
        }
    }
}
